import * as icons from 'ionicons/icons';

export const themeIcons = {
    add: icons.add,
    reader: icons.reader,
    remove: icons.trash,
    search: icons.search,
    close: icons.close,
    settings: icons.settings,
    menu: icons.menu,
    arrowBack: icons.arrowBack,
    bandage: icons.bandage,
    barbell: icons.barbell,
    build: icons.build,
    car: icons.car,
    dice: icons.dice,
    fastFood: icons.fastFood,
    female: icons.female,
    male: icons.male,
    cube: icons.cube,
    fileTrayFull: icons.fileTrayFull,
    flower: icons.flower,
    image: icons.image,
    location: icons.location,
    sad: icons.sad,
    skull: icons.skull,
    today: icons.today,
}
